### PR TITLE
Feat: V0.29 Update ModelReorganizer to use internal IDs for entry.id

### PR DESCRIPTION
**Pull request by piehld**
Feat: V0.29 Update ModelReorganizer to use internal IDs for entry.id (for internal use only)

### CODE REVIEW

**Comment by josemduarte** [comment]
Thanks @piehld . Will this mean that the output CIF file will be fully consistent in terms of the entry_id being the same throughout the file (if I understand it right, the entry_id appears in a couple of places beyond entry.id)

**Comment by piehld** [comment]
@josemduarte Good point, I'm still doing some development (created the PR prematurely so that it would run through Azure tests too). But yeah, the entry id appears in the following attributes (as well as the `data_` block):
```
data_AF-O24891-F1
_entry.id   AF-O24891-F1 
_database_2.database_code   AF-O24891-F1 
_pdbx_database_status.entry_id                        AF-O24891-F1 
_struct_ref_seq.pdbx_PDB_id_code              AF-O24891-F1 
```
I'll need to talk with @brindakv about how to handle these other cases, but in general, it sounds like we should just replace all of them with internal IDs, no?

**Comment by josemduarte** [comment]
> but in general, it sounds like we should just replace all of them with internal IDs, no?

Yes I think so

**Comment by brindakv** [comment]
@piehld All the data items that you point out will need to be updated.

**Comment by brindakv** [comment]
@piehld @josemduarte `_database_2.database_code` should correspond to `_database_2.database_id` and cannot be changed. We'll have to look at `_pdbx_database_status.entry_id` because this corresponds to the status of the entry in the database.

**Comment by piehld** [comment]
@brindakv Thanks. And regarding `database_2`, since that's loopable, I should loop over every ID right?

**Comment by brindakv** [comment]
@piehld @josemduarte We should not change anything in `database_2` because the data here should correspond to the source database. I am looking into how to handle `pdbx_database_status`. We should perhaps remove the entire table because if we leave it, it will result in parent-child relationship issues with `_entry.id` and we cannot change it because it corresponds to the source database.

**Comment by piehld** [comment]
Thanks for clarifying @brindakv, I misread your earlier comment. And OK, if removing it is easier, maybe let's do that. It's not in the MA models anyway, so clearly it's not critical to the pipeline.

What about `_ma_entry_associated_files` though? Since the files themselves are named with the original filename, shouldn't we keep that?

**Review by brindakv — APPROVED** [review]
@piehld Looks good to me. Thanks.

**Pull request merged**
